# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'codepushTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for codepushTest
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  

  platform :ios, '9.0'
  target 'codepushTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'codepushTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for codepushTest-tvOS

  target 'codepushTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
